//literals
// let a=['apple','green apple','mango','kiwi','pine apple','starwberry','plum','orange','berries'];
// console.log(a[6]);

// //constructor
// let b=new Array('sachin','dhoni','boomrah','kohli','rahul','shami');
// console.log(b[2]);

// //heterogeneous--->different datatypes in a single array
// let arr=['string',3,true];
// console.log(arr[2]);

//ARRAY WITH LOOP
var arr=[1,2,3,4,5];
for(var i=0;i<=arr.length-1;i++)
{
    console.log(arr[i]);
}